name = "sub-smaiclub-top"
compatibility_date = "2026-04-27"
pages_build_output_dir = "dist"

[vars]
SUB_PUBLIC_ORIGIN = "https://sub.smaiclub.top"
SUB_TRAFFIC_TOTAL_BYTES = "536870912000"
EDGETUNNEL_MAX_NODES = "99"

[[d1_databases]]
binding = "DB"
database_name = "user_db"
database_id = "0b100581-db8c-46a3-92f8-55d2ee05c30a"
migrations_dir = "migrations"
