name: CI/CD - 2026

on:
  push:
    paths:
      - "2026.smaiclub.top/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_static-pages.yml
    with:
      site_directory: 2026.smaiclub.top
      project_name: 2026-smaiclub-top
    secrets: inherit
