name: CI/CD - Blog

on:
  push:
    paths:
      - "blog.smaiclub.top/**"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/_static-pages.yml
    with:
      site_directory: blog.smaiclub.top
      project_name: blog-smaiclub-top
    secrets: inherit
