name: CI/CD - Dash

on:
  push:
    paths:
      - "dash.smaiclub.top/**"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/_static-pages.yml
    with:
      site_directory: dash.smaiclub.top
      project_name: dash-smaiclub-top
    secrets: inherit
