name: CI/CD - Download

on:
  push:
    paths:
      - "download.smaiclub.top/**"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      deployments: write
    uses: ./.github/workflows/_static-pages.yml
    with:
      site_directory: download.smaiclub.top
      project_name: download-smaiclub-top
    secrets: inherit
