name: CI/CD - News

on:
  push:
    paths:
      - "news.smaiclub.top/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_static-pages.yml
    with:
      site_directory: news.smaiclub.top
      project_name: news-smaiclub-top
    secrets: inherit
